#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_CONTAINER="${APP_CONTAINER:?APP_CONTAINER is required}"
LOG_SINCE="${LOG_SINCE:?LOG_SINCE is required}"
SQL_FIRST_SENTINEL="${SQL_FIRST_SENTINEL:?SQL_FIRST_SENTINEL is required}"
SQL_FINAL_SENTINEL="${SQL_FINAL_SENTINEL:?SQL_FINAL_SENTINEL is required}"
SQL_EVIDENCE_ARTIFACT="${SQL_EVIDENCE_ARTIFACT:?SQL_EVIDENCE_ARTIFACT is required}"
SQL_EVIDENCE_ATTESTATION="${SQL_EVIDENCE_ATTESTATION:?SQL_EVIDENCE_ATTESTATION is required}"
SQL_EVIDENCE_READY_FILE="${SQL_EVIDENCE_READY_FILE:?SQL_EVIDENCE_READY_FILE is required}"
SQL_GZIP_MAX_BYTES="${SQL_GZIP_MAX_BYTES:?SQL_GZIP_MAX_BYTES is required}"

capture_env=(env -i "PATH=${PATH}" "HOME=${HOME:-}" "TMPDIR=${TMPDIR:-/tmp}")
[[ -z "${DOCKER_CONFIG:-}" ]] || capture_env+=("DOCKER_CONFIG=${DOCKER_CONFIG}")
[[ -z "${DOCKER_HOST:-}" ]] || capture_env+=("DOCKER_HOST=${DOCKER_HOST}")

exec "${capture_env[@]}" SQL_GZIP_MAX_BYTES="${SQL_GZIP_MAX_BYTES}" \
	APP_CONTAINER="${APP_CONTAINER}" LOG_SINCE="${LOG_SINCE}" \
	SQL_FIRST_SENTINEL="${SQL_FIRST_SENTINEL}" SQL_FINAL_SENTINEL="${SQL_FINAL_SENTINEL}" \
	node "${ROOT_DIR}/sql-evidence.mjs" capture-docker \
		"${SQL_EVIDENCE_ARTIFACT}" "${SQL_EVIDENCE_ATTESTATION}" "${SQL_EVIDENCE_READY_FILE}" \
		"${SQL_FIRST_SENTINEL}" "${SQL_FINAL_SENTINEL}"
