package com.faithlog.notification.domain;

public enum NotificationType {
	DEVOTION_REMINDER,
	DEVOTION_MISSING,
	WED_POLL_OPEN,
	WED_POLL_MISSING,
	SATURDAY_POLL_OPEN,
	SATURDAY_POLL_MISSING,
	COFFEE_POLL_OPEN,
	COFFEE_POLL_MISSING,
	PAYMENT_UNPAID,
	CUSTOM
}
