package com.faithlog.notification.domain.type;

public enum NotificationType {
	DEVOTION_REMINDER,
	DEVOTION_MISSING,
	WED_POLL_OPEN,
	WED_POLL_MISSING,
	SATURDAY_POLL_OPEN,
	SATURDAY_POLL_MISSING,
	COFFEE_POLL_OPEN,
	COFFEE_POLL_MISSING,
	MEAL_POLL_OPEN,
	CUSTOM_POLL_OPEN,
	PAYMENT_UNPAID,
	ANNOUNCEMENT_PUBLISHED,
	WEEKLY_SHARING_SHEET_PUBLISHED,
	CUSTOM
}
