CREATE TABLE yearly_recap_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    recap_year INTEGER NOT NULL,
    has_recap_data BOOLEAN NOT NULL,
    devotion_quiet_time_count INTEGER NOT NULL,
    devotion_bible_reading_count INTEGER NOT NULL,
    devotion_prayer_count INTEGER NOT NULL,
    devotion_all_completed_day_count INTEGER NOT NULL,
    devotion_submitted_week_count INTEGER NOT NULL,
    devotion_longest_streak_days INTEGER NOT NULL,
    devotion_most_active_month INTEGER,
    prayer_submitted_week_count INTEGER NOT NULL,
    prayer_participated_season_count INTEGER NOT NULL,
    poll_participated_count INTEGER NOT NULL,
    poll_wed_service_count INTEGER NOT NULL,
    poll_saturday_leader_count INTEGER NOT NULL,
    poll_coffee_count INTEGER NOT NULL,
    poll_meal_count INTEGER NOT NULL,
    poll_custom_count INTEGER NOT NULL,
    poll_comment_count INTEGER NOT NULL,
    first_presented_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_yearly_recap_snapshots_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_yearly_recap_snapshots_user_year UNIQUE (user_id, recap_year),
    CONSTRAINT ck_yearly_recap_snapshots_year CHECK (recap_year BETWEEN 2000 AND 9999),
    CONSTRAINT ck_yearly_recap_snapshots_most_active_month CHECK (
        devotion_most_active_month IS NULL OR devotion_most_active_month BETWEEN 1 AND 12
    ),
    CONSTRAINT ck_yearly_recap_snapshots_counts CHECK (
        devotion_quiet_time_count >= 0
        AND devotion_bible_reading_count >= 0
        AND devotion_prayer_count >= 0
        AND devotion_all_completed_day_count >= 0
        AND devotion_submitted_week_count >= 0
        AND devotion_longest_streak_days >= 0
        AND prayer_submitted_week_count >= 0
        AND prayer_participated_season_count >= 0
        AND poll_participated_count >= 0
        AND poll_wed_service_count >= 0
        AND poll_saturday_leader_count >= 0
        AND poll_coffee_count >= 0
        AND poll_meal_count >= 0
        AND poll_custom_count >= 0
        AND poll_comment_count >= 0
    )
);

CREATE TABLE yearly_recap_campuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    yearly_recap_snapshot_id BIGINT NOT NULL,
    campus_id BIGINT NOT NULL,
    campus_name VARCHAR(100) NOT NULL,
    joined_date DATE NOT NULL,
    joined_during_recap_year BOOLEAN NOT NULL,
    CONSTRAINT fk_yearly_recap_campuses_snapshot FOREIGN KEY (yearly_recap_snapshot_id) REFERENCES yearly_recap_snapshots (id),
    CONSTRAINT uk_yearly_recap_campuses_snapshot_campus UNIQUE (yearly_recap_snapshot_id, campus_id)
);

ALTER TABLE yearly_recap_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE yearly_recap_campuses ENABLE ROW LEVEL SECURITY;
