CREATE TABLE yearly_recap_archive_facts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fact_type VARCHAR(30) NOT NULL,
    source_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    recap_year INTEGER NOT NULL,
    campus_id BIGINT,
    activity_date DATE,
    grouping_id BIGINT,
    secondary_grouping_id BIGINT,
    flag_one BOOLEAN,
    flag_two BOOLEAN,
    flag_three BOOLEAN,
    status_value VARCHAR(30),
    amount_value BIGINT,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_yearly_recap_archive_facts_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_yearly_recap_archive_facts_campus
        FOREIGN KEY (campus_id) REFERENCES campuses (id) ON DELETE CASCADE,
    CONSTRAINT uk_yearly_recap_archive_facts_type_source UNIQUE (fact_type, source_id),
    CONSTRAINT ck_yearly_recap_archive_facts_type CHECK (
        fact_type IN ('COMMENT', 'PRAYER', 'DEVOTION_DAILY', 'DEVOTION_WEEKLY', 'PENALTY')
    ),
    CONSTRAINT ck_yearly_recap_archive_facts_year CHECK (recap_year BETWEEN 2000 AND 9999),
    CONSTRAINT ck_yearly_recap_archive_facts_amount CHECK (amount_value IS NULL OR amount_value >= 0),
    CONSTRAINT ck_yearly_recap_archive_facts_penalty_status CHECK (
        fact_type <> 'PENALTY' OR status_value IN ('PAID', 'UNPAID')
    )
);

CREATE INDEX idx_yearly_recap_archive_facts_user_year_type
    ON yearly_recap_archive_facts (user_id, recap_year, fact_type);

CREATE TABLE yearly_recap_archive_coverage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fact_type VARCHAR(30) NOT NULL,
    complete_from_year INTEGER NOT NULL,
    CONSTRAINT uk_yearly_recap_archive_coverage_type UNIQUE (fact_type),
    CONSTRAINT ck_yearly_recap_archive_coverage_type CHECK (
        fact_type IN ('COMMENT', 'PRAYER', 'DEVOTION_DAILY', 'DEVOTION_WEEKLY', 'PENALTY')
    ),
    CONSTRAINT ck_yearly_recap_archive_coverage_year CHECK (complete_from_year BETWEEN 2000 AND 9999)
);

INSERT INTO yearly_recap_archive_coverage (fact_type, complete_from_year)
SELECT fact_type, EXTRACT(YEAR FROM CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Seoul')::INTEGER + 1
FROM (VALUES
    ('COMMENT'),
    ('PRAYER'),
    ('DEVOTION_DAILY'),
    ('DEVOTION_WEEKLY'),
    ('PENALTY')
) AS source(fact_type);

ALTER TABLE yearly_recap_archive_facts ENABLE ROW LEVEL SECURITY;
ALTER TABLE yearly_recap_archive_coverage ENABLE ROW LEVEL SECURITY;
