CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at TIMESTAMP(6) WITH TIME ZONE,
    token_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'MANAGER', 'ADMIN'))
);

CREATE TABLE campuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    region VARCHAR(100),
    description TEXT,
    invite_code VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_campuses_invite_code UNIQUE (invite_code)
);

CREATE TABLE campus_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    campus_role VARCHAR(30) NOT NULL DEFAULT 'MEMBER',
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    joined_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_campus_members_campus_user UNIQUE (campus_id, user_id),
    CONSTRAINT ck_campus_members_role CHECK (campus_role IN ('MINISTER', 'ELDER', 'CAMPUS_LEADER', 'MEMBER')),
    CONSTRAINT ck_campus_members_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE campus_duty_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    duty_type VARCHAR(30) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    assigned_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_campus_duty_assignments_type CHECK (duty_type IN ('COFFEE'))
);

CREATE TABLE penalty_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus_id BIGINT NOT NULL,
    rule_type VARCHAR(30) NOT NULL,
    calculation_type VARCHAR(30) NOT NULL,
    required_count INTEGER NOT NULL DEFAULT 0,
    base_amount INTEGER NOT NULL DEFAULT 0,
    amount_per_unit INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_penalty_rules_rule_type CHECK (rule_type IN ('QUIET_TIME', 'PRAYER', 'BIBLE_READING', 'SATURDAY_LATE')),
    CONSTRAINT ck_penalty_rules_calculation_type CHECK (calculation_type IN ('MISSING_COUNT', 'LATE_MINUTE'))
);

CREATE TABLE payment_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus_id BIGINT NOT NULL,
    account_type VARCHAR(30) NOT NULL,
    nickname VARCHAR(100) NOT NULL,
    bank_name VARCHAR(100) NOT NULL,
    account_number VARCHAR(100) NOT NULL,
    account_holder VARCHAR(100) NOT NULL,
    owner_user_id BIGINT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    deactivated_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_payment_accounts_account_type CHECK (account_type IN ('PENALTY', 'COFFEE'))
);

CREATE TABLE weekly_devotion_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    week_start_date DATE NOT NULL,
    week_end_date DATE NOT NULL,
    quiet_time_count INTEGER NOT NULL DEFAULT 0,
    prayer_count INTEGER NOT NULL DEFAULT 0,
    bible_reading_count INTEGER NOT NULL DEFAULT 0,
    saturday_late_minutes INTEGER NOT NULL DEFAULT 0,
    submitted_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_weekly_devotion_records_campus_user_week UNIQUE (campus_id, user_id, week_start_date)
);

CREATE TABLE devotion_daily_checks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weekly_record_id BIGINT NOT NULL,
    record_date DATE NOT NULL,
    quiet_time_checked BOOLEAN NOT NULL DEFAULT FALSE,
    prayer_checked BOOLEAN NOT NULL DEFAULT FALSE,
    bible_reading_checked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_devotion_daily_checks_weekly_record_date UNIQUE (weekly_record_id, record_date)
);

CREATE TABLE coffee_brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_code VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_coffee_brands_brand_code UNIQUE (brand_code)
);

CREATE TABLE coffee_menu_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id BIGINT NOT NULL,
    menu_code VARCHAR(100) NOT NULL,
    name VARCHAR(200) NOT NULL,
    price_amount INTEGER NOT NULL DEFAULT 0,
    category VARCHAR(60) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_coffee_menu_catalog_brand_menu UNIQUE (brand_id, menu_code)
);

CREATE TABLE poll_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    poll_type VARCHAR(40) NOT NULL,
    selection_type VARCHAR(30) NOT NULL DEFAULT 'SINGLE',
    charge_generation_type VARCHAR(40) NOT NULL DEFAULT 'NONE',
    payment_category VARCHAR(30),
    payment_account_id BIGINT,
    allow_user_option_add BOOLEAN NOT NULL DEFAULT FALSE,
    auto_create_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    start_day_of_week INTEGER NOT NULL,
    start_time TIME(6) WITHOUT TIME ZONE NOT NULL,
    end_day_of_week INTEGER NOT NULL,
    end_time TIME(6) WITHOUT TIME ZONE NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_poll_templates_poll_type CHECK (poll_type IN ('WED_SERVICE', 'SATURDAY_LEADER', 'COFFEE', 'CUSTOM')),
    CONSTRAINT ck_poll_templates_selection_type CHECK (selection_type IN ('SINGLE', 'MULTIPLE')),
    CONSTRAINT ck_poll_templates_charge_generation_type CHECK (charge_generation_type IN ('NONE', 'OPTION_PRICE')),
    CONSTRAINT ck_poll_templates_payment_category CHECK (payment_category IS NULL OR payment_category IN ('PENALTY', 'COFFEE'))
);

CREATE TABLE poll_template_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT NOT NULL,
    content VARCHAR(200) NOT NULL,
    compose_menu_code VARCHAR(100),
    price_amount INTEGER NOT NULL DEFAULT 0,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE polls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus_id BIGINT NOT NULL,
    template_id BIGINT,
    title VARCHAR(200) NOT NULL,
    poll_type VARCHAR(40) NOT NULL,
    selection_type VARCHAR(30) NOT NULL DEFAULT 'SINGLE',
    is_anonymous BOOLEAN NOT NULL DEFAULT FALSE,
    allow_user_option_add BOOLEAN NOT NULL DEFAULT FALSE,
    charge_generation_type VARCHAR(40) NOT NULL DEFAULT 'NONE',
    payment_category VARCHAR(30),
    payment_account_id BIGINT,
    starts_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    ends_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'SCHEDULED',
    created_by BIGINT,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_polls_poll_type CHECK (poll_type IN ('WED_SERVICE', 'SATURDAY_LEADER', 'COFFEE', 'CUSTOM')),
    CONSTRAINT ck_polls_selection_type CHECK (selection_type IN ('SINGLE', 'MULTIPLE')),
    CONSTRAINT ck_polls_charge_generation_type CHECK (charge_generation_type IN ('NONE', 'OPTION_PRICE')),
    CONSTRAINT ck_polls_payment_category CHECK (payment_category IS NULL OR payment_category IN ('PENALTY', 'COFFEE')),
    CONSTRAINT ck_polls_status CHECK (status IN ('SCHEDULED', 'OPEN', 'CLOSED'))
);

CREATE TABLE poll_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id BIGINT NOT NULL,
    content VARCHAR(200) NOT NULL,
    compose_menu_code VARCHAR(100),
    price_amount INTEGER NOT NULL DEFAULT 0,
    sort_order INTEGER NOT NULL DEFAULT 0,
    user_added BOOLEAN NOT NULL DEFAULT FALSE,
    created_by_user_id BIGINT
);

CREATE TABLE poll_responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    memo VARCHAR(500),
    responded_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_poll_responses_poll_user UNIQUE (poll_id, user_id)
);

CREATE TABLE poll_response_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    response_id BIGINT NOT NULL,
    option_id BIGINT NOT NULL,
    CONSTRAINT uk_poll_response_options_response_option UNIQUE (response_id, option_id)
);

CREATE TABLE poll_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content VARCHAR(1000) NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE charge_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    payment_category VARCHAR(30) NOT NULL,
    payment_account_id BIGINT NOT NULL,
    bank_name_snapshot VARCHAR(100) NOT NULL,
    account_number_snapshot VARCHAR(100) NOT NULL,
    account_holder_snapshot VARCHAR(100) NOT NULL,
    source_type VARCHAR(30) NOT NULL,
    source_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    reason VARCHAR(255),
    amount INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'UNPAID',
    due_date DATE,
    paid_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_charge_items_source UNIQUE (campus_id, user_id, payment_category, source_type, source_id),
    CONSTRAINT ck_charge_items_payment_category CHECK (payment_category IN ('PENALTY', 'COFFEE')),
    CONSTRAINT ck_charge_items_source_type CHECK (source_type IN ('DEVOTION_RECORD', 'POLL_RESPONSE')),
    CONSTRAINT ck_charge_items_status CHECK (status IN ('UNPAID', 'PAID', 'WAIVED', 'CANCELED'))
);

CREATE TABLE prayer_seasons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_by BIGINT,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_prayer_seasons_status CHECK (status IN ('ACTIVE', 'CLOSED'))
);

CREATE TABLE prayer_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE prayer_group_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    joined_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_prayer_group_members_group_user UNIQUE (group_id, user_id)
);

CREATE TABLE prayer_weeks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus_id BIGINT NOT NULL,
    season_id BIGINT NOT NULL,
    week_start_date DATE NOT NULL,
    week_end_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_prayer_weeks_campus_season_week UNIQUE (campus_id, season_id, week_start_date),
    CONSTRAINT ck_prayer_weeks_status CHECK (status IN ('OPEN', 'CLOSED'))
);

CREATE TABLE prayer_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prayer_week_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content TEXT,
    submitted_by BIGINT,
    submitted_at TIMESTAMP(6) WITH TIME ZONE,
    version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_prayer_submissions_week_user UNIQUE (prayer_week_id, user_id)
);

CREATE TABLE user_fcm_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token TEXT NOT NULL,
    client_instance_id VARCHAR(100) NOT NULL,
    device_type VARCHAR(30) NOT NULL,
    app_version VARCHAR(50),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_seen_at TIMESTAMP(6) WITH TIME ZONE,
    last_refreshed_at TIMESTAMP(6) WITH TIME ZONE,
    last_failure_reason TEXT,
    deactivated_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_user_fcm_tokens_token UNIQUE (token),
    CONSTRAINT ck_user_fcm_tokens_device_type CHECK (device_type IN ('ANDROID', 'IOS', 'WEB'))
);

CREATE TABLE notification_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id UUID NOT NULL,
    user_id BIGINT NOT NULL,
    campus_id BIGINT NOT NULL,
    notification_type VARCHAR(50) NOT NULL,
    target_week_start_date DATE,
    target_id BIGINT,
    title VARCHAR(200) NOT NULL,
    body TEXT NOT NULL,
    send_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    failure_reason TEXT,
    sent_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_notification_logs_type CHECK (
        notification_type IN (
            'DEVOTION_REMINDER',
            'DEVOTION_MISSING',
            'WED_POLL_OPEN',
            'WED_POLL_MISSING',
            'SATURDAY_POLL_OPEN',
            'SATURDAY_POLL_MISSING',
            'COFFEE_POLL_OPEN',
            'COFFEE_POLL_MISSING',
            'PAYMENT_UNPAID',
            'CUSTOM'
        )
    ),
    CONSTRAINT ck_notification_logs_send_status CHECK (send_status IN ('PENDING', 'SENT', 'FAILED', 'SKIPPED'))
);

CREATE UNIQUE INDEX uk_campus_duty_assignments_active_duty
    ON campus_duty_assignments (campus_id, duty_type)
    WHERE is_active = TRUE;
CREATE UNIQUE INDEX uk_penalty_rules_active_rule
    ON penalty_rules (campus_id, rule_type)
    WHERE is_active = TRUE;
CREATE UNIQUE INDEX uk_payment_accounts_active_type
    ON payment_accounts (campus_id, account_type)
    WHERE is_active = TRUE;
CREATE INDEX idx_notification_logs_request_id ON notification_logs (request_id);
CREATE INDEX idx_notification_logs_campus_type_status_created
    ON notification_logs (campus_id, notification_type, send_status, created_at);
CREATE INDEX idx_user_fcm_tokens_user_client_active
    ON user_fcm_tokens (user_id, client_instance_id, is_active);

ALTER TABLE campus_members
    ADD CONSTRAINT fk_campus_members_campus FOREIGN KEY (campus_id) REFERENCES campuses (id),
    ADD CONSTRAINT fk_campus_members_user FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE campus_duty_assignments
    ADD CONSTRAINT fk_campus_duty_assignments_campus FOREIGN KEY (campus_id) REFERENCES campuses (id),
    ADD CONSTRAINT fk_campus_duty_assignments_user FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE penalty_rules
    ADD CONSTRAINT fk_penalty_rules_campus FOREIGN KEY (campus_id) REFERENCES campuses (id);
ALTER TABLE payment_accounts
    ADD CONSTRAINT fk_payment_accounts_campus FOREIGN KEY (campus_id) REFERENCES campuses (id),
    ADD CONSTRAINT fk_payment_accounts_owner_user FOREIGN KEY (owner_user_id) REFERENCES users (id);
ALTER TABLE weekly_devotion_records
    ADD CONSTRAINT fk_weekly_devotion_records_campus FOREIGN KEY (campus_id) REFERENCES campuses (id),
    ADD CONSTRAINT fk_weekly_devotion_records_user FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE devotion_daily_checks
    ADD CONSTRAINT fk_devotion_daily_checks_weekly_record FOREIGN KEY (weekly_record_id) REFERENCES weekly_devotion_records (id);
ALTER TABLE coffee_menu_catalog
    ADD CONSTRAINT fk_coffee_menu_catalog_brand FOREIGN KEY (brand_id) REFERENCES coffee_brands (id);
ALTER TABLE poll_templates
    ADD CONSTRAINT fk_poll_templates_campus FOREIGN KEY (campus_id) REFERENCES campuses (id),
    ADD CONSTRAINT fk_poll_templates_payment_account FOREIGN KEY (payment_account_id) REFERENCES payment_accounts (id);
ALTER TABLE poll_template_options
    ADD CONSTRAINT fk_poll_template_options_template FOREIGN KEY (template_id) REFERENCES poll_templates (id);
ALTER TABLE polls
    ADD CONSTRAINT fk_polls_campus FOREIGN KEY (campus_id) REFERENCES campuses (id),
    ADD CONSTRAINT fk_polls_template FOREIGN KEY (template_id) REFERENCES poll_templates (id),
    ADD CONSTRAINT fk_polls_payment_account FOREIGN KEY (payment_account_id) REFERENCES payment_accounts (id),
    ADD CONSTRAINT fk_polls_created_by FOREIGN KEY (created_by) REFERENCES users (id);
ALTER TABLE poll_options
    ADD CONSTRAINT fk_poll_options_poll FOREIGN KEY (poll_id) REFERENCES polls (id),
    ADD CONSTRAINT fk_poll_options_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES users (id);
ALTER TABLE poll_responses
    ADD CONSTRAINT fk_poll_responses_poll FOREIGN KEY (poll_id) REFERENCES polls (id),
    ADD CONSTRAINT fk_poll_responses_user FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE poll_response_options
    ADD CONSTRAINT fk_poll_response_options_response FOREIGN KEY (response_id) REFERENCES poll_responses (id),
    ADD CONSTRAINT fk_poll_response_options_option FOREIGN KEY (option_id) REFERENCES poll_options (id);
ALTER TABLE poll_comments
    ADD CONSTRAINT fk_poll_comments_poll FOREIGN KEY (poll_id) REFERENCES polls (id),
    ADD CONSTRAINT fk_poll_comments_user FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE charge_items
    ADD CONSTRAINT fk_charge_items_campus FOREIGN KEY (campus_id) REFERENCES campuses (id),
    ADD CONSTRAINT fk_charge_items_user FOREIGN KEY (user_id) REFERENCES users (id),
    ADD CONSTRAINT fk_charge_items_payment_account FOREIGN KEY (payment_account_id) REFERENCES payment_accounts (id);
ALTER TABLE prayer_seasons
    ADD CONSTRAINT fk_prayer_seasons_campus FOREIGN KEY (campus_id) REFERENCES campuses (id),
    ADD CONSTRAINT fk_prayer_seasons_created_by FOREIGN KEY (created_by) REFERENCES users (id);
ALTER TABLE prayer_groups
    ADD CONSTRAINT fk_prayer_groups_season FOREIGN KEY (season_id) REFERENCES prayer_seasons (id);
ALTER TABLE prayer_group_members
    ADD CONSTRAINT fk_prayer_group_members_group FOREIGN KEY (group_id) REFERENCES prayer_groups (id),
    ADD CONSTRAINT fk_prayer_group_members_user FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE prayer_weeks
    ADD CONSTRAINT fk_prayer_weeks_campus FOREIGN KEY (campus_id) REFERENCES campuses (id),
    ADD CONSTRAINT fk_prayer_weeks_season FOREIGN KEY (season_id) REFERENCES prayer_seasons (id);
ALTER TABLE prayer_submissions
    ADD CONSTRAINT fk_prayer_submissions_prayer_week FOREIGN KEY (prayer_week_id) REFERENCES prayer_weeks (id),
    ADD CONSTRAINT fk_prayer_submissions_group FOREIGN KEY (group_id) REFERENCES prayer_groups (id),
    ADD CONSTRAINT fk_prayer_submissions_user FOREIGN KEY (user_id) REFERENCES users (id),
    ADD CONSTRAINT fk_prayer_submissions_submitted_by FOREIGN KEY (submitted_by) REFERENCES users (id);
ALTER TABLE user_fcm_tokens
    ADD CONSTRAINT fk_user_fcm_tokens_user FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE notification_logs
    ADD CONSTRAINT fk_notification_logs_user FOREIGN KEY (user_id) REFERENCES users (id),
    ADD CONSTRAINT fk_notification_logs_campus FOREIGN KEY (campus_id) REFERENCES campuses (id);
