CREATE TABLE shepherd_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    normalized_name VARCHAR(100) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_by BIGINT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_shepherd_groups_campus_normalized_name UNIQUE (campus_id, normalized_name),
    CONSTRAINT fk_shepherd_groups_campus FOREIGN KEY (campus_id) REFERENCES campuses(id),
    CONSTRAINT fk_shepherd_groups_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT ck_shepherd_groups_status CHECK (status IN ('ACTIVE', 'ARCHIVED')),
    CONSTRAINT ck_shepherd_groups_name_not_blank CHECK (length(btrim(name)) > 0),
    CONSTRAINT ck_shepherd_groups_normalized_name_not_blank CHECK (length(btrim(normalized_name)) > 0),
    CONSTRAINT ck_shepherd_groups_version_positive CHECK (version >= 1)
);

CREATE TABLE shepherd_group_assignees (
    shepherd_group_id BIGINT NOT NULL,
    campus_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    assigned_by BIGINT NOT NULL,
    assigned_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_shepherd_group_assignees PRIMARY KEY (shepherd_group_id, user_id),
    CONSTRAINT fk_shepherd_group_assignees_group FOREIGN KEY (shepherd_group_id) REFERENCES shepherd_groups(id),
    CONSTRAINT fk_shepherd_group_assignees_campus FOREIGN KEY (campus_id) REFERENCES campuses(id),
    CONSTRAINT fk_shepherd_group_assignees_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_shepherd_group_assignees_assigned_by FOREIGN KEY (assigned_by) REFERENCES users(id),
    CONSTRAINT fk_shepherd_group_assignees_member FOREIGN KEY (campus_id, user_id)
        REFERENCES campus_members(campus_id, user_id)
);

CREATE TABLE weekly_shepherd_attendance_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus_id BIGINT NOT NULL,
    shepherd_group_id BIGINT NOT NULL,
    service_date DATE NOT NULL,
    small_group_meeting_count INTEGER NOT NULL DEFAULT 0,
    holy_wave_count INTEGER NOT NULL DEFAULT 0,
    other_worship_count INTEGER NOT NULL DEFAULT 0,
    note VARCHAR(500),
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    created_by BIGINT NOT NULL,
    last_modified_by BIGINT NOT NULL,
    last_modified_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_weekly_shepherd_attendance_group_date UNIQUE (shepherd_group_id, service_date),
    CONSTRAINT fk_weekly_shepherd_attendance_campus FOREIGN KEY (campus_id) REFERENCES campuses(id),
    CONSTRAINT fk_weekly_shepherd_attendance_group FOREIGN KEY (shepherd_group_id) REFERENCES shepherd_groups(id),
    CONSTRAINT fk_weekly_shepherd_attendance_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_weekly_shepherd_attendance_last_modified_by FOREIGN KEY (last_modified_by) REFERENCES users(id),
    CONSTRAINT ck_weekly_shepherd_attendance_status CHECK (status IN ('DRAFT', 'SUBMITTED')),
    CONSTRAINT ck_weekly_shepherd_attendance_sunday CHECK (extract(dow from service_date) = 0),
    CONSTRAINT ck_weekly_shepherd_attendance_counts_nonnegative CHECK (
        small_group_meeting_count >= 0
        AND holy_wave_count >= 0
        AND other_worship_count >= 0
    ),
    CONSTRAINT ck_weekly_shepherd_attendance_version_positive CHECK (version >= 1)
);

CREATE INDEX idx_shepherd_groups_campus_status_normalized_id
    ON shepherd_groups(campus_id, status, normalized_name, id);

CREATE INDEX idx_shepherd_group_assignees_user_campus_group
    ON shepherd_group_assignees(user_id, campus_id, shepherd_group_id);

CREATE INDEX idx_shepherd_group_assignees_campus_group_user
    ON shepherd_group_assignees(campus_id, shepherd_group_id, user_id);

CREATE INDEX idx_weekly_shepherd_attendance_campus_date_group
    ON weekly_shepherd_attendance_reports(campus_id, service_date, shepherd_group_id);

ALTER TABLE shepherd_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE shepherd_group_assignees ENABLE ROW LEVEL SECURITY;
ALTER TABLE weekly_shepherd_attendance_reports ENABLE ROW LEVEL SECURITY;
